container:
    image: registry.fedoraproject.org/fedora

build_task:
    name: CI
    env:
        HOME: /root
    build_script: |
        dnf -y install bats golang make podman btrfs-progs-devel gpgme-devel device-mapper-devel
        gcc -v
        go version
        make
